# Build APKs for Kiwi Browser
name: automatic build of apk

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [arm, arm64, x86, x64]

    # The GitHub Actions machines have a "slow disk", and a SSD "fast" disk.
    # However, there is not enough space to do all the processing on the SSD.
    
    # We refer to the disks based on their name in /dev/disk

    # /dev/disk/azure/root-part1 is / ("slow disk")
    # /dev/disk/azure/resource-part1 is a 14 GB ephemeral SSD disk mounted in /mnt

    # We store the source-code repository (kiwibrowser/src) on /dev/disk/azure/root-part1
    # We store cache, dependencies and output on /dev/disk/azure/resource-part1 (SSD)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Initializing build
        run: echo Initializing build for platform ${{ matrix.platform }}

      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

#      Uncomment if you need additional space (takes about 2 minutes)
#      - name: Reclaiming disk space on / by removing .NET framework
#        run: sudo rm -rf /usr/share/dotnet

      - name: Checking-out source-code in $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Creating secondary disk folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          sudo mkdir -p /mnt/secondary_disk
          sudo chown -R runner:docker /mnt/secondary_disk
          
      - name: Creating symlink on /dev/disk/azure/root-part1 pointing to /dev/disk/azure/resource-part1
        run: ln -s /mnt/secondary_disk $GITHUB_WORKSPACE/

      # We cannot checkout outside of $GITHUB_WORKSPACE, but we want to checkout to the SSD
      # so we have a symbolic link $GITHUB_WORKSPACE/secondary_disk/ pointing to the SSD
      # and checkout the code there
      - name: Checking-out CIPD dependencies in /mnt/secondary_disk/.cipd
        uses: actions/checkout@v2
        with:
          repository: kiwibrowser/dependencies
          path: ./secondary_disk/.cipd 

      - name: Linking .cipd in the proper path and copying .gclient and .gclient_entries
        run: |
          ln -s $GITHUB_WORKSPACE/./secondary_disk/.cipd ..
          cp ../.cipd/.gclient ..
          cp ../.cipd/.gclient_entries ..

      - name: Installing rclone
        run: curl https://rclone.org/install.sh | sudo bash -s beta

      - name: Updating APT repository
        run: sudo apt-get update

      - name: Installing Python and OpenJDK
        run: sudo apt-get install -y python openjdk-8-jdk-headless libncurses5 ccache

      - name: Setting-up Java 8 as default Java provider
        run: sudo update-java-alternatives --set java-1.8.0-openjdk-amd64

      - name: Installing system dependencies
        run: |
          sudo bash install-build-deps.sh --no-chromeos-fonts
          build/linux/sysroot_scripts/install-sysroot.py --arch=i386
          build/linux/sysroot_scripts/install-sysroot.py --arch=amd64

      - name: Creating output folder
        run: mkdir -p secondary_disk/out/android_${{ matrix.platform }}

      - name: Generating one-time APK signature key
        run: keytool -genkey -v -keystore keystore.jks -alias dev -keyalg RSA -keysize 2048 -validity 10000 -storepass public_password -keypass public_password -dname "cn=Kiwi Browser (unverified), ou=Actions, o=Kiwi Browser, c=GitHub"

      - name: Copying args.gn to target folder
        run: cat .build/android_arm/args.gn | sed "s#target_cpu = \"arm\"#target_cpu = \"${{ matrix.platform }}\"#" | sed "s#android_default_version_name = \"Git\"#android_default_version_name = \"Git$(date '+%y%m%d')\"#" > secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Modifying args.gn (arm)
        if: matrix.platform == 'arm'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')1\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Modifying args.gn (arm64)
        if: matrix.platform == 'arm64'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')2\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Modifying args.gn (x86)
        if: matrix.platform == 'x86'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')3\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Modifying args.gn (x64)
        if: matrix.platform == 'x64'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')4\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Displaying args.gn
        run: cat secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Downloading depot_tools
        working-directory: ./secondary_disk
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Adding depot_tools to path
        run: echo "::add-path::$GITHUB_WORKSPACE/secondary_disk/depot_tools"

      - name: Setting environment variables
        run: |
          echo "::set-env name=CC::ccache clang -Qunused-arguments"
          echo "::set-env name=CXX::ccache clang++ -Qunused-arguments"

      - name: Checking available disk-space
        run: df -h

      - name: Creating rclone config
        run: |
          mkdir -p $HOME/.config/rclone/
          echo '[cache]' > $HOME/.config/rclone/rclone.conf
          echo 'type = s3' >> $HOME/.config/rclone/rclone.conf
          echo 'provider = Wasabi' >> $HOME/.config/rclone/rclone.conf
          echo 'env_auth = false' >> $HOME/.config/rclone/rclone.conf
          echo 'endpoint = s3.wasabisys.com' >> $HOME/.config/rclone/rclone.conf
          echo 'acl = public-read' >> $HOME/.config/rclone/rclone.conf

      - name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          sudo mkdir -p /mnt/cache
          sudo chown -R runner:docker /mnt/cache
          
      - name: Creating symlink in $HOME/cache pointing to cache on /dev/disk/azure/resource-part1
        run: ln -s /mnt/cache $HOME/

      - name: Downloading binary objects cache to $HOME/cache
        run: rclone copy --fast-list --transfers=16 cache:kiwibrowser-ccache-${{ matrix.platform }} $HOME/cache

      - name: Checking available disk-space after downloading cache
        run: df -h
        
      - name: Calculating cache size
        run: du -csh $HOME/cache

      - name: Creating ccache configuration
        run: |
          mkdir -p $HOME/.ccache/
          echo 'compiler_check = none' >> $HOME/.ccache/ccache.conf
          echo "stats = false" >> $HOME/.ccache/ccache.conf
          echo 'max_size = 20G' >> $HOME/.ccache/ccache.conf
          echo "base_dir = $HOME" >> $HOME/.ccache/ccache.conf
          echo "cache_dir = $HOME/cache" >> $HOME/.ccache/ccache.conf
          echo "hash_dir = false" >> $HOME/.ccache/ccache.conf

      - name: Running gclient runhooks
        run: gclient runhooks

      - name: Generating build files
        run: gn gen ./secondary_disk/out/android_${{ matrix.platform }}

      - name: Checking available disk-space before build cache
        run: df -h

      - name: Creating rclone config to upload the cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        run: |
          echo '[sync]' > $HOME/.config/rclone/rclone.conf
          echo 'type = s3' >> $HOME/.config/rclone/rclone.conf
          echo 'provider = Wasabi' >> $HOME/.config/rclone/rclone.conf
          echo 'env_auth = true' >> $HOME/.config/rclone/rclone.conf
          echo 'endpoint = s3.wasabisys.com' >> $HOME/.config/rclone/rclone.conf
          echo 'acl = public-read' >> $HOME/.config/rclone/rclone.conf

      # We compile component by component as 6 hours is not enough for the initial build
      # so we can snapshot between each component and continue further from the snapshot
      - name: Compiling source-code (base)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} base

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (chrome_java)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} chrome_java

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (components/version_info)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} components/version_info

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (chrome/browser)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} chrome/browser

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (chrome/common)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} chrome/common

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (chrome/gpu)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} chrome/gpu

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (chrome/renderer)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} chrome/renderer

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (extensions)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} extensions

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (services)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} services

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Compiling source-code (v8)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} v8

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
        run: rclone copy --fast-list --transfers=16 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/

      - name: Checking available disk-space
        run: df -h

      - name: Reclaiming disk space
        run: sudo rm -rf /mnt/cache/*

      - name: Checking available disk-space
        run: df -h

      - name: Checking available memory
        run: free -m

      - name: Listing running processes
        run: ps auxww

      - name: Compiling source-code (final stage)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} chrome_public_apk

      - name: Uploading APK
        uses: actions/upload-artifact@v1
        with:
          name: apk-${{ matrix.platform }}
          path: ./secondary_disk/out/android_${{ matrix.platform }}/apks/

  sign_and_upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Creating release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: true
          body: |
            This release was automatically generated from GitHub ${{ github.ref }} in Workflow ID ${{ github.run_id }} and is signed using a random development key (upgrades / updates are not possible).

      - name: Downloading artifact (arm)
        uses: actions/download-artifact@v1
        with:
          name: apk-arm

      - name: Uploading release asset (arm)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apk-arm/ChromePublic.apk
          asset_name: Kiwi-${{ github.run_id }}-arm.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Downloading artifact (arm64)
        uses: actions/download-artifact@v1
        with:
          name: apk-arm64

      - name: Uploading release asset (arm64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apk-arm64/ChromePublic.apk
          asset_name: Kiwi-${{ github.run_id }}-arm64.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Downloading artifact (x86)
        uses: actions/download-artifact@v1
        with:
          name: apk-x86

      - name: Uploading release asset (x86)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apk-x86/ChromePublic.apk
          asset_name: Kiwi-${{ github.run_id }}-x86.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Downloading artifact (x64)
        uses: actions/download-artifact@v1
        with:
          name: apk-x64

      - name: Uploading release asset (x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apk-x64/ChromePublic.apk
          asset_name: Kiwi-${{ github.run_id }}-x64.apk
          asset_content_type: application/vnd.android.package-archive
